In [ ]:
import numpy as np
arr1 = np.arange(1, 11)
print(arr1)

arr2 = np.arange(1, 10).reshape(3, 3)
print(arr2)

arr3 = np.random.rand(3, 5, 3)
print(arr3)

print(arr1.shape, arr1.size, arr1.dtype)
print(arr2.shape, arr2.size, arr2.dtype)
print(arr3.shape, arr3.size, arr3.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[0.22945188 0.74226589 0.11543264]
  [0.6414808  0.18414536 0.2219739 ]
  [0.27938325 0.91303046 0.72395262]
  [0.87238755 0.14683106 0.4087595 ]
  [0.31508712 0.97959115 0.89419985]]

 [[0.74060541 0.70152919 0.799217  ]
  [0.20940756 0.34431569 0.17604271]
  [0.11977414 0.84110428 0.64224347]
  [0.18564329 0.00153544 0.48933548]
  [0.41923414 0.55034797 0.19645127]]

 [[0.19687796 0.44162988 0.7842872 ]
  [0.7254189  0.43805305 0.76917228]
  [0.73067368 0.24815743 0.6797789 ]
  [0.16544453 0.69191612 0.98302175]
  [0.49215119 0.68888828 0.01506785]]]
(10,) 10 int32
(3, 3) 9 int32
(3, 5, 3) 45 float64


In [3]:
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print(data[:3])          
print(data[::2]) 
print(data[::-1])       

[10 20 30]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


In [4]:
# Mathematical Ops
A = np.random.randint(1, 21, 5)
B = np.random.randint(1, 21, 5)

print("A:", A)
print("B:", B)

print("Add:", A + B)
print("Subtract:", A - B)
print("Multiply:", A * B)
print("Divide:", A / B)

print("Dot Product:", np.dot(A, B))

print("A Mean:", np.mean(A))
print("A Median:", np.median(A))
print("A Std:", np.std(A))
print("A Var:", np.var(A))

print("B Max:", np.max(B), "at index", np.argmax(B))
print("B Min:", np.min(B), "at index", np.argmin(B))

A: [ 5  3 15 16  7]
B: [ 4  2  3 18  9]
Add: [ 9  5 18 34 16]
Subtract: [ 1  1 12 -2 -2]
Multiply: [ 20   6  45 288  63]
Divide: [1.25       1.5        5.         0.88888889 0.77777778]
Dot Product: 422
A Mean: 9.2
A Median: 7.0
A Std: 5.30659966456864
A Var: 28.160000000000004
B Max: 18 at index 3
B Min: 2 at index 1


In [5]:
# Reshaping And Trnasposing
arr = np.arange(1, 13)

arr2d = arr.reshape(4, 3)
print(arr2d)

arr3d = arr.reshape(2, 2, 3)
print(arr3d)

transposed = arr2d.T
print(transposed)
print("Transposed shape:", transposed.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Transposed shape: (3, 4)


In [6]:
# Boolean masking and filtering 
arr = np.random.randint(10, 51, 15)
print("Array:", arr)

print("Elements >25:", arr[arr > 25])

arr[arr < 30] = 0
print("After replacing <30 with 0:", arr)

print("Count divisible by 5:", np.sum(arr % 5 == 0))

Array: [38 47 27 19 19 37 34 44 18 24 42 13 30 33 46]
Elements >25: [38 47 27 37 34 44 42 30 33 46]
After replacing <30 with 0: [38 47  0  0  0 37 34 44  0  0 42  0 30 33 46]
Count divisible by 5: 7


In [7]:
# Working with built in functions
print(np.linspace(0, 1, 10))

print(np.eye(4))

arr = np.random.randint(1, 101, 20)
arr.sort()
print("Sorted:", arr)
print("5 largest:", arr[-5:])

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Sorted: [ 5 12 16 19 28 29 30 30 36 37 38 59 59 61 61 66 67 91 94 94]
5 largest: [66 67 91 94 94]
